# Generated by Django 5.1.1 on 2024-09-29 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите ваш доход', max_digits=10, verbose_name='Сумма дохода')),
                ('date', models.DateField(verbose_name='Дата получения дохода')),
                ('source', models.CharField(max_length=100, verbose_name='Источник дохода(например зарплата и т.п.)')),
                ('category', models.CharField(max_length=100, verbose_name='Категория дохода(например основной или дополнительных доход)')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
